name: Build and Deploy MASTER on Push

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy MASTER to EC2
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
        run: |
          echo "${EC2_SSH_KEY}" > ssh_key
          chmod 600 ssh_key
          ssh -o StrictHostKeyChecking=no -i ssh_key $EC2_USER@$EC2_HOST << 'EOF'
            cd hof/HOF-Website
            git pull origin master
            
            # Stop existing instance on port 5050 if running
            while true; do
              if sudo lsof -i :5050 > /dev/null 2>&1; then
                  echo "Process found on port 5050. Attempting to kill..."
                  sudo kill -9 $(sudo netstat -tulnp | grep :5050 | awk '{print $7}' | cut -d'/' -f1)
                  sleep 5
              else
                  echo "No process found on port 5050. Moving on."
                  break
              fi
            done
            
            # Start new instance on port 5050
            nohup taskset -c 2 gunicorn --workers=3 --bind=0.0.0.0:5050 app:app > nohup.out 2>&1 &

          EOF
